stages:
  data_ingestion:
    cmd: python src\pipeline\stage_01_data_ingestion.py
    deps:
      - src\pipeline\stage_01_data_ingestion.py
    outs:
      - artifacts\DataIngestion\images
      - artifacts\DataIngestion\RSNA.zip
  
  model_training_:
    cmd: python src\pipeline\stage_02_model_training.py
    deps:
      - src\pipeline\stage_02_model_training.py
    outs:
      - artifacts\ModelTrainings\model.h5